### ISSUE TITLE
Publish APK on Github?

### ISSUE THREAD

**Issue by IzzySoft** [samanyougarg/ABR-App-Backup-Restore#1]
First congrats to your new app! Being open source: would you mind publishing the `.apk` here on Github as well – especially for those without Playstore? The easiest way would be [using Github's release feature](https://help.github.com/articles/creating-releases/). Wouldn't take much more than a minute to put the file there :)

Thanks in advance!

**Comment by samanyougarg** [comment]
Hey!
Thanks for your suggestion. I have uploaded the apk.

**Comment by IzzySoft** [comment]
Thanks a lot! To promote it to the non-Google world, you can now also [find it in my repository](https://apt.izzysoft.de/fdroid/index/apk/com.appisode.appbackuprestore), which can be used with the F-Droid client. :+1:
